<!DOCTYPE html>
<html lang="en">
<head>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="http://xion.io/$theme/stylesheet/style.min.css">

  <link rel="stylesheet" type="text/css" href="http://xion.io/$theme/stylesheet/pygments.min.css">
  <link rel="stylesheet" type="text/css" href="http://xion.io/$theme/stylesheet/font-awesome.min.css">

    <link href="http://xion.io/style.css" rel="stylesheet">




  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="" />

<meta name="author" content="Karol Kuczmarski" />
<meta name="description" content="A relatively little known feature of Python is the else block for control flow statements other than if. If you haven’t heard about it before, you can provide such a block for both while and for loops, as well as any variant of the try statement, Its functionality is roughly analogous in both cases: in loops, the else block is executed if the loop didn’t exit abnormally (i.e. with break) in try constructs, the else block runs if no exception happened Likely because of the unique semantics that don’t exist in other languages, neither of those constructs has been seen much in real world code. Recently, however, I’ve found they can be combined into a very pythonic pattern that’s also quite useful. The trick Say you have a task that won’t always succeed. Perhaps it’s a request made to a janky server, or other network operartion that’s prone to timeouts. Since failures are likely to be transient, you’d like to retry it several more times before giving up permanently. With try/except block, you can detect those half-expected failures. With a simple loop, you can repeat the attempt for as many times as you deem feasible. Combined, they can solve the problem rather neatly: for _ in range(MAX_RETRIES): try: # ... do stuff ... except SomeTransientError: # ... log it, sleep, etc. ... continue else: break else: raise PermanentError() But why? What’s the deal with the elses here, though? Are they both necessary? The simple answer is of course no. else after either a loop or try/except block is always a syntactic sugar. Any code that contains it can be transformed into an equivalent snippet that utilizes different techniques to achieve the same effect. But this view isn’t very useful, for many of the essential features in any programming languages can be dismissed as superfluous using this reasoning. The real question is whether the above idiom is more readable and understandable than the alternatives. To that, I posit, the answer is: absolutely. Desugaring Without the double else, this example would have to be written in a considerably more convoluted way: retries = MAX_RETRIES while retries &gt; 0: try: # ... do stuff ... break except SomeTransientError: # ... log it, sleep, etc. ... retries -= 1 if retries == 0: raise PermanentError() Although at first glance the difference may be minuscule, this version adds significant extra busywork the programmer has to pay careful attention to: The retries variable now has to be explicit, because the final conditional statement must look at its value. We can’t use a for loop anymore (e.g. for retries in range(MAX_RETRIES)), because we wouldn’t distinguish the “success at last try” and “retry limit exceeded” cases: they’d both result in retries equal to MAX_RETRIES - 1 after the loop1. As a result, we have to remember to decrement the counter ourselves upon an error. Additionally, the break is easy to miss amidst the actual logic within the try block, both for developer who writes the code and for any subsequent readers. An alternative is to move it outside of the try/except clause, but that in turn reintroduces continue into the except branch and further complicates the whole flow. In short, the desugared version is more error-prone (all those off-by-ones!) and also quite inscrutable. Or to 1, if we count from MAX_RETRIES down to zero. ↩" />
<meta name="keywords" content="Python, exceptions, else">
<meta property="og:site_name" content="Karol Kuczmarski's Blog"/>
<meta property="og:title" content="Retry idiom for Python"/>
<meta property="og:description" content="A relatively little known feature of Python is the else block for control flow statements other than if. If you haven’t heard about it before, you can provide such a block for both while and for loops, as well as any variant of the try statement, Its functionality is roughly analogous in both cases: in loops, the else block is executed if the loop didn’t exit abnormally (i.e. with break) in try constructs, the else block runs if no exception happened Likely because of the unique semantics that don’t exist in other languages, neither of those constructs has been seen much in real world code. Recently, however, I’ve found they can be combined into a very pythonic pattern that’s also quite useful. The trick Say you have a task that won’t always succeed. Perhaps it’s a request made to a janky server, or other network operartion that’s prone to timeouts. Since failures are likely to be transient, you’d like to retry it several more times before giving up permanently. With try/except block, you can detect those half-expected failures. With a simple loop, you can repeat the attempt for as many times as you deem feasible. Combined, they can solve the problem rather neatly: for _ in range(MAX_RETRIES): try: # ... do stuff ... except SomeTransientError: # ... log it, sleep, etc. ... continue else: break else: raise PermanentError() But why? What’s the deal with the elses here, though? Are they both necessary? The simple answer is of course no. else after either a loop or try/except block is always a syntactic sugar. Any code that contains it can be transformed into an equivalent snippet that utilizes different techniques to achieve the same effect. But this view isn’t very useful, for many of the essential features in any programming languages can be dismissed as superfluous using this reasoning. The real question is whether the above idiom is more readable and understandable than the alternatives. To that, I posit, the answer is: absolutely. Desugaring Without the double else, this example would have to be written in a considerably more convoluted way: retries = MAX_RETRIES while retries &gt; 0: try: # ... do stuff ... break except SomeTransientError: # ... log it, sleep, etc. ... retries -= 1 if retries == 0: raise PermanentError() Although at first glance the difference may be minuscule, this version adds significant extra busywork the programmer has to pay careful attention to: The retries variable now has to be explicit, because the final conditional statement must look at its value. We can’t use a for loop anymore (e.g. for retries in range(MAX_RETRIES)), because we wouldn’t distinguish the “success at last try” and “retry limit exceeded” cases: they’d both result in retries equal to MAX_RETRIES - 1 after the loop1. As a result, we have to remember to decrement the counter ourselves upon an error. Additionally, the break is easy to miss amidst the actual logic within the try block, both for developer who writes the code and for any subsequent readers. An alternative is to move it outside of the try/except clause, but that in turn reintroduces continue into the except branch and further complicates the whole flow. In short, the desugared version is more error-prone (all those off-by-ones!) and also quite inscrutable. Or to 1, if we count from MAX_RETRIES down to zero. ↩"/>
<meta property="og:locale" content="en_US"/>
<meta property="og:url" content="http://xion.io/post/code/python-retry-idiom.html"/>
<meta property="og:type" content="article"/>
<meta property="article:published_time" content="2016-01-27 17:48:00-08:00"/>
<meta property="article:modified_time" content=""/>
<meta property="article:author" content="http://xion.io/">
<meta property="article:section" content="Code"/>
<meta property="article:tag" content="Python"/>
<meta property="article:tag" content="exceptions"/>
<meta property="article:tag" content="else"/>
<meta property="og:image" content="http://xion.io/logo.jpeg">
  <title>Karol Kuczmarski's Blog &ndash; Retry idiom for Python</title>
</head>
<body>
  <aside>
    <div>
      <a href="http://xion.io">
        <img src="http://xion.io/logo.jpeg" alt="Karol Kuczmarski" title="Karol Kuczmarski">
      </a>
      <h1><a href="http://xion.io">Karol Kuczmarski</a></h1>
      <p>fn(Tea) -> Code</p>
      <nav>
        <ul class="list">
          <li><a href="http://xion.io/page/about.html#about">About</a></li>
          <li><a href="http://xion.io/page/projects.html#projects">Projects</a></li>
        </ul>
      </nav>
      <ul class="social">
        <li><a class="sc-github" href="http://github.com/Xion" target="_blank"><i class="fa fa-github"></i></a></li>
        <li><a class="sc-stack-overflow" href="http://stackoverflow.com/users/434799/xion" target="_blank"><i class="fa fa-stack-overflow"></i></a></li>
        <li><a class="sc-twitter" href="http://twitter.com/Xion__" target="_blank"><i class="fa fa-twitter"></i></a></li>
        <li><a class="sc-google" href="https://plus.google.com/+KarolKuczmarski" target="_blank"><i class="fa fa-google"></i></a></li>
        <li><a class="sc-rss" href="/feeds/atom.xml" target="_blank"><i class="fa fa-rss"></i></a></li>
      </ul>
    </div>
  </aside>
  <main>
    <nav>
      <a href="http://xion.io">Home</a>
      <a href="/archives.html">Archives</a>
      <a href="/categories.html">Categories</a>
      <a href="/tags.html">Tags</a>
      <a href="http://xion.org.pl/">Old blog</a>
    </nav>

<article>
  <header>
    <h1 id="python-retry-idiom">Retry idiom for&nbsp;Python</h1>
    <p>Posted on Wed 27 January 2016 in <a href="http://xion.io/category/code.html">Code</a></p>
  </header>
  <div>
    <p>A relatively little known feature of Python is the <code>else</code> block for control flow statements other than <code>if</code>.</p>
<p>If you haven&#8217;t heard about it before, you can provide such a block for both <code>while</code> and <code>for</code> loops,
as well as any variant of the <code>try</code> statement, Its functionality is roughly analogous in both&nbsp;cases:</p>
<ul>
<li>in loops, the <code>else</code> block is executed if the loop didn&#8217;t exit abnormally (i.e. with <code>break</code>)</li>
<li>in <code>try</code> constructs, the <code>else</code> block runs if <em>no</em> exception&nbsp;happened</li>
</ul>
<p>Likely because of the unique semantics that don&#8217;t exist in other languages, neither of those constructs has been seen much
in real world code. Recently, however, I&#8217;ve found they can be combined into a very pythonic pattern
that&#8217;s also quite&nbsp;useful.</p>
<h4>The&nbsp;trick</h4>
<p>Say you have a task that won&#8217;t always succeed. Perhaps it&#8217;s a request made to a janky server, or other network operartion
that&#8217;s prone to timeouts. Since failures are likely to be transient, you&#8217;d like to retry it several more times before
giving up&nbsp;permanently.</p>
<p>With <code>try</code>/<code>except</code> block, you can detect those half-expected failures. With a simple loop, you can repeat the attempt
for as many times as you deem feasible. Combined, they can solve the problem rather&nbsp;neatly:</p>
<div class="highlight"><pre><span class="k">for</span> <span class="n">_</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">MAX_RETRIES</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="c"># ... do stuff ...</span>
    <span class="k">except</span> <span class="n">SomeTransientError</span><span class="p">:</span>
        <span class="c"># ... log it, sleep, etc. ...</span>
        <span class="k">continue</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">break</span>
<span class="k">else</span><span class="p">:</span>
    <span class="k">raise</span> <span class="n">PermanentError</span><span class="p">()</span>
</pre></div>


<h4>But&nbsp;why?</h4>
<p>What&#8217;s the deal with the <code>else</code>s here, though? Are they both&nbsp;necessary?</p>
<p>The simple answer is of course no. <code>else</code> after either a loop or  <code>try</code>/<code>except</code> block is always a <em>syntactic sugar</em>.
Any code that contains it can be transformed into an equivalent snippet that utilizes different techniques to achieve
the same&nbsp;effect.</p>
<p>But this view isn&#8217;t very useful, for many of the essential features in any programming languages can be dismissed
as superfluous using this reasoning. The real question is whether the above idiom is more readable and understandable
than the&nbsp;alternatives.</p>
<p>To that, I posit, the answer is: <em>absolutely</em>.</p>
<h4>Desugaring</h4>
<p>Without the double <code>else</code>, this example would have to be written in a considerably more convoluted&nbsp;way:</p>
<div class="highlight"><pre><span class="n">retries</span> <span class="o">=</span> <span class="n">MAX_RETRIES</span>
<span class="k">while</span> <span class="n">retries</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="c"># ... do stuff ...</span>
        <span class="k">break</span>
    <span class="k">except</span> <span class="n">SomeTransientError</span><span class="p">:</span>
        <span class="c"># ... log it, sleep, etc. ...</span>
        <span class="n">retries</span> <span class="o">-=</span> <span class="mi">1</span>
<span class="k">if</span> <span class="n">retries</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
    <span class="k">raise</span> <span class="n">PermanentError</span><span class="p">()</span>
</pre></div>


<p>Although at first glance the difference may be minuscule, this version adds significant extra busywork the programmer
has to pay careful attention&nbsp;to:</p>
<ul>
<li>The <code>retries</code> variable now has to be explicit, because the final conditional statement must look at its&nbsp;value.</li>
<li>We can&#8217;t use a <code>for</code> loop anymore (e.g. <code>for retries in range(MAX_RETRIES)</code>), because we wouldn&#8217;t distinguish the
&#8220;success at last try&#8221; and &#8220;retry limit exceeded&#8221; cases: they&#8217;d both result in <code>retries</code> equal to <code>MAX_RETRIES - 1</code>
after the loop<sup id="fnref:1"><a class="footnote-ref" href="#fn:1" rel="footnote">1</a></sup>.</li>
<li>As a result, we have to remember to decrement the counter ourselves upon an&nbsp;error.</li>
</ul>
<p>Additionally, the <code>break</code> is easy to miss amidst the actual logic within the <code>try</code> block, both for developer
who writes the code and for any subsequent readers. An alternative is to move it outside of the <code>try</code>/<code>except</code> clause,
but that in turn reintroduces <code>continue</code> into the <code>except</code> branch and further complicates the whole&nbsp;flow.</p>
<p>In short, the desugared version is more error-prone (all those off-by-ones!) and also quite&nbsp;inscrutable.</p>
<div class="footnote">
<hr />
<ol>
<li id="fn:1">
<p>Or to <code>1</code>, if we count from <code>MAX_RETRIES</code> down to zero.&#160;<a class="footnote-backref" href="#fnref:1" rev="footnote" title="Jump back to footnote 1 in the text">&#8617;</a></p>
</li>
</ol>
</div>
  </div>
  <div class="tag-cloud">
    <p>
      <a href="http://xion.io/tag/python.html">Python</a>
      <a href="http://xion.io/tag/exceptions.html">exceptions</a>
      <a href="http://xion.io/tag/else.html">else</a>
    </p>
  </div>
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'xionblog';
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</article>

    <footer>
<p>
  &copy; Karol Kuczmarski 2016 - This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>
</p>
<p>Built using <a href="http://getpelican.com" target="_blank">Pelican</a> - <a href="https://github.com/alexandrevicenzi/flex" target="_blank">Flex</a> theme by <a href="http://alexandrevicenzi.com" target="_blank">Alexandre Vicenzi</a></p><p>
  <a rel="license"
     href="http://creativecommons.org/licenses/by-sa/4.0/"
     target="_blank">
    <img alt="Creative Commons License"
         title="Creative Commons License"
         style="border-width:0"
         src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png"
         width="80"
         height="15"/>
  </a>
</p>    </footer>
  </main>

<!-- Google Analytics -->
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-27379564-1', 'auto');
  ga('send', 'pageview');
</script>
<!-- End Google Analytics -->



<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BlogPosting",
  "name": "Retry idiom for Python",
  "headline": "Retry idiom for Python",
  "datePublished": "2016-01-27 17:48:00-08:00",
  "dateModified": "",
  "author": {
    "@type": "Person",
    "name": "Karol Kuczmarski",
    "url": "http://xion.io/"
  },
  "image": "http://xion.io/logo.jpeg",
  "url": "http://xion.io/post/code/python-retry-idiom.html",
  "description": "A relatively little known feature of Python is the else block for control flow statements other than if. If you haven’t heard about it before, you can provide such a block for both while and for loops, as well as any variant of the try statement, Its functionality is roughly analogous in both cases: in loops, the else block is executed if the loop didn’t exit abnormally (i.e. with break) in try constructs, the else block runs if no exception happened Likely because of the unique semantics that don’t exist in other languages, neither of those constructs has been seen much in real world code. Recently, however, I’ve found they can be combined into a very pythonic pattern that’s also quite useful. The trick Say you have a task that won’t always succeed. Perhaps it’s a request made to a janky server, or other network operartion that’s prone to timeouts. Since failures are likely to be transient, you’d like to retry it several more times before giving up permanently. With try/except block, you can detect those half-expected failures. With a simple loop, you can repeat the attempt for as many times as you deem feasible. Combined, they can solve the problem rather neatly: for _ in range(MAX_RETRIES): try: # ... do stuff ... except SomeTransientError: # ... log it, sleep, etc. ... continue else: break else: raise PermanentError() But why? What’s the deal with the elses here, though? Are they both necessary? The simple answer is of course no. else after either a loop or try/except block is always a syntactic sugar. Any code that contains it can be transformed into an equivalent snippet that utilizes different techniques to achieve the same effect. But this view isn’t very useful, for many of the essential features in any programming languages can be dismissed as superfluous using this reasoning. The real question is whether the above idiom is more readable and understandable than the alternatives. To that, I posit, the answer is: absolutely. Desugaring Without the double else, this example would have to be written in a considerably more convoluted way: retries = MAX_RETRIES while retries > 0: try: # ... do stuff ... break except SomeTransientError: # ... log it, sleep, etc. ... retries -= 1 if retries == 0: raise PermanentError() Although at first glance the difference may be minuscule, this version adds significant extra busywork the programmer has to pay careful attention to: The retries variable now has to be explicit, because the final conditional statement must look at its value. We can’t use a for loop anymore (e.g. for retries in range(MAX_RETRIES)), because we wouldn’t distinguish the “success at last try” and “retry limit exceeded” cases: they’d both result in retries equal to MAX_RETRIES - 1 after the loop1. As a result, we have to remember to decrement the counter ourselves upon an error. Additionally, the break is easy to miss amidst the actual logic within the try block, both for developer who writes the code and for any subsequent readers. An alternative is to move it outside of the try/except clause, but that in turn reintroduces continue into the except branch and further complicates the whole flow. In short, the desugared version is more error-prone (all those off-by-ones!) and also quite inscrutable. Or to 1, if we count from MAX_RETRIES down to zero. ↩"
}
</script></body>
</html>